### ISSUE TITLE
Bug with new Fire TV 2

### ISSUE THREAD

**Issue by slack8181** [sphinx02/FireStarter#13]
I installed 2.7.2 on the new fire tv 2 and it works correctly but i keep getting a notification that brings up some service that keeps starting and stopping. Any way to correct this?

**Comment by malone7201** [comment]
So the main app screen seems to be working on the new FireTV but home button detection does now. Specifically the notifications I'm seeing are something along the lines of "Exception: Failed to clear logcat" and "Firestarter: Something went wrong, restarting HomeButtonObserver". Logcat from initial application launch attached.

**Comment by imagica71** [comment]
you have to disable adb debugging and re-enable it, then the errors are gone. (this is just an temp fix) ;-)

i found another bug: i set kodi to start on double clicking the home button, but it seems to start or switch to kodi multiple times because the kodi menu ist flickering 4-5 times...

**Comment by malone7201** [comment]
Sweet, worked great. Looks like the ADB toggle is required anytime the box is reloaded. I had the flickering issue as well when double clicking to launch Kodi, setting the Jump Back Watchdog Timer to 0 (disabled) cleared it up for me.

Dev is active on XDA and sounds like he is working on fixes.

**Comment by imagica71** [comment]
Quit Kodi and launch it by double clicking home then it will flicker again. Seems that it does not when kodi is already running.

**Comment by malone7201** [comment]
hmm, no i'm not experiencing the same behavior with the Jump Back Timer disabled even after I force stop Kodi and relaunch with double click

**Comment by imagica71** [comment]
yes, you are right! I thought it was set to zero ... no flickering anymore! :-)

**Comment by vip32** [comment]
re-enabling adb does not solve the issue

**Comment by sphinx02** [comment]
Disable & enable (toggle) ADB after reboot is not anymore needed. Still no parallel ADB connections possible. Jumpback Watchdog problems are fixed, you can safely set it back to default of 5000ms.

see https://github.com/sphinx02/FireStarter/releases/tag/v3.0

**Comment by rven6200** [comment]
I also got that same error message. But the fix that I found was permanent, After alot of searcing online I found that the solution was to go into the firestarter settings and on the box that is checked that says ' fallback to non adb observation mode" ( or something like that) Uncheck that box and then do a reboot by pressing the select and the play button together for 5 seconds and when it reboots  I was able to double click the home button to launch kodi like normal and I didnt have an error message pop up.  After that I have never seen that error since
