### ISSUE TITLE
KODI 16.0?

### ISSUE THREAD

**Issue by LaffinAtcha** [sphinx02/FireStarter#25]
Is there a way so this only updates KODI to 15.2 since 16 is only a beta release and doesn't play well with Fire Tv at this time?

**Comment by delaware1999** [comment]
Since 2 Days the FIre starter says in the settings that there is a new Version KODI 16 availible.
This version is still Beta.. Why does it say that ?
is that a error, or do you guys from Firestarter Team have a Final Version of KODI 16 ?
And when I try to update it doesnt work. there is comming a error. On my Fire TV Box 4K and normal Box and fire TV stick

**Comment by sphinx02** [comment]
http://forum.xda-developers.com/showpost.php?p=63875080&postcount=351

**Comment by sphinx02** [comment]
Fixed in https://github.com/sphinx02/FireStarter/releases/tag/v3.2.1
