### ISSUE TITLE
New Update ! Dont want it !

### ISSUE THREAD

**Issue by delaware1999** [sphinx02/FireStarter#57]
Hello I am using Firestopper !  And I still want to use it.
But from today on there is comming every minute a Msg that there is 4.0 Version availible !
I dont want to use 4.0 Version because it doesnt skip the Amazon Login on the first Bootup from the fire tv
Can you please remove that my Version trys to download every minute the 4.0 download ?!  Or add this function again please that skips the Amazon Login ! !

**Comment by sphinx02** [comment]
First of all, if you deny the update once, FireStarter / AppStarter will never ask again to update!

I can totally understand if you do not like the fact, that two of the main features of FireStarter are not anymore useable in AppStarter (Home-Button-Detection and Auto-Start). And I can also understand if you are using a Fork of FireStarter like FireStopper or if you stay at any older version of FireStarter. But anyway, my decision is clear to that point, AppStarter will not have one of these two features in future, as I am quite sure, Amazon will block AppStarter like they did it with FireStarter. I think AppStarter is very useful also without these two features. With a double-click to the home-button the app-overview is opened where AppStarter is always the first App if you stick it as favourite App. From there you are only one click away from opening AppStarter.
I guess the point "Some of the users don't like registering" or "Users want to bypass the Amazon User Interface" are exactly why Amazon has blocked FireStarter. I really do not like to play cat and mouse with Amazon by changing the Packetname of AppStarter every 2 weeks to bypass new entries on the blocklist. I mostly profit from the feature to keep Kodi up-to-date at the moment and I hope Amazon will not block AppStarter only because of this ability.

For everyone who really dont want to see any Amazon related things I can only recommend to buy another streaming device or to follow any of the rooting tutorials out there. For me rooting is no choice and so I try to find a way, to keep AppStarter unblocked by Amazon.
